services:
  app_1:
    build: .
    image: parchi:latest
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTANCE_ID=instance_1
      - PORT=8080
    networks:
      - parchi-network

  app_2:
    build: .
    image: parchi:latest
    ports:
      - "8081:8081"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - INSTANCE_ID=instance_2
      - PORT=8081
    networks:
      - parchi-network

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - parchi-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    depends_on:
      - app_1
      - app_2
      - redis
    networks:
      - parchi-network

volumes:
  redis-data:

networks:
  parchi-network:
    driver: bridge
