FROM openresty/openresty:alpine

# Copy your NGINX configuration file into the container
# COPY ./nginx.conf /etc/nginx/nginx.conf

# Install additional dependencies if needed
RUN apk update && apk add --no-cache curl bash
